
tasks:
  - init: npm install && npm run build
    command: npm run start && gp preview $(gp url 4200)
  - name: Install Angular CLI
    init: gp sync-done installation
    command: npm install -g @angular/cli
  - name: Working CLI
    init: gp sync-done installation
    command: echo "Enter here your personal commands"
    openMode: tab-after
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
